name:                kanji
version:             0.1.0.0
github:              "kavinvin/kanji"
license:             BSD3
author:              "Kavin Ruengprateepsang"
maintainer:          "kavinvin.vin@gmail.com"
copyright:           "2018 Kavin Ruengprateepsang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kavinvin/kanji#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  kanji-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kanji

tests:
  kanji-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kanji
